---
kind: pipeline
type: docker
name: android

concurrency:
  limit: 1

steps:
- name: build
  image: mingc/android-build-box:1.20.0
  commands:
  - ./gradlew build
  
- name: Create a signed .apk
  image: mingc/android-build-box:1.20.0
  when:
    branch:
    - master
  environment:
    KEY_LOCATION:
      from_secret: key-location
    STORE_PASSWORD:
      from_secret: mateusz-bak.key-store-password
    KEY_ALIAS:
      from_secret: mateusz-bak.key-alias
    KEY_PASSWORD:
      from_secret: mateusz-bak.key-password
  commands:
  - wget -q $KEY_LOCATION
  - cp mateusz-bak.jks app/mateusz-bak.jks
  - ./gradlew assembleRelease -Pandroid.injected.signing.store.file=mateusz-bak.jks -Pandroid.injected.signing.store.password=$STORE_PASSWORD -Pandroid.injected.signing.key.alias=$KEY_ALIAS -Pandroid.injected.signing.key.password=$KEY_PASSWORD
  - ls -l app/build/outputs/apk/release
...
