name: openreads
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.1.0
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  path: ^1.8.2
  flutter_displaymode: ^0.4.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.0
  flutter_bloc: ^8.1.1
  colours: ^0.0.2
  flutter_blurhash: ^0.7.0
  blurhash_dart: ^1.1.0
  image: ^3.2.2
  fl_chart: ^0.55.2
  intl: ^0.17.0
  dropdown_button2: ^1.8.9
  equatable: ^2.0.5
  connectivity_plus: ^3.0.2
  http: ^0.13.5
  cached_network_image: ^3.2.2
  loading_animation_widget: ^1.2.0+3
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
